version: "3.9"

services:
  database:
    container_name: postgres
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db_password
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  webserver:
    build: .
    container_name: web
    ports:
      - "8080:8080"
    secrets:
      - db_password
    depends_on:
      database:
        condition: service_healthy

secrets:
  db_password:
    file: ./db_pass.txt
